"""Anant Intern — Plug and Play Setup Wizard."""

import os
import subprocess
from typing import Optional
from pydantic import BaseModel


class SetupConfig(BaseModel):
    """Setup configuration from the wizard."""
    
    # Slack
    slack_bot_token: Optional[str] = None
    slack_signing_secret: Optional[str] = None
    slack_app_token: Optional[str] = None
    
    # GitHub
    github_token: Optional[str] = None
    
    # Jira
    jira_url: Optional[str] = None
    jira_email: Optional[str] = None
    jira_api_token: Optional[str] = None
    jira_project_key: Optional[str] = None
    
    # Agent
    default_agent: str = "claude-code"
    agent_routing: str = "smart"
    
    # API Keys
    anthropic_api_key: Optional[str] = None
    openai_api_key: Optional[str] = None
    xai_api_key: Optional[str] = None
    
    # Local LLM
    use_local_llm: bool = False
    ollama_model: str = "qwen2.5-coder:7b"
    
    # Repos (comma-separated)
    repos: Optional[str] = None


def run_setup_wizard(config: SetupConfig) -> dict:
    """
    Run the setup wizard.
    
    1. Validate config
    2. Write .env file
    3. Test connections
    4. Pull repos
    5. Return status
    """
    results = {
        "success": False,
        "steps": [],
        "errors": [],
    }
    
    # Step 1: Validate
    steps = []
    
    # Check Slack
    if config.slack_bot_token and config.slack_signing_secret:
        steps.append({"name": "Slack", "status": "configured"})
    else:
        steps.append({"name": "Slack", "status": "skipped", "reason": "No tokens provided"})
    
    # Check GitHub
    if config.github_token:
        steps.append({"name": "GitHub", "status": "configured"})
    else:
        steps.append({"name": "GitHub", "status": "skipped", "reason": "No token provided"})
    
    # Check Jira
    if config.jira_url and config.jira_email and config.jira_api_token:
        steps.append({"name": "Jira", "status": "configured"})
    else:
        steps.append({"name": "Jira", "status": "skipped", "reason": "Incomplete credentials"})
    
    # Check Agent
    agent_key_map = {
        "claude-code": "anthropic_api_key",
        "codex": "openai_api_key",
        "cursor": "anthropic_api_key",
        "grok": "xai_api_key",
    }
    
    required_key = agent_key_map.get(config.default_agent)
    if required_key and getattr(config, required_key):
        steps.append({"name": f"Agent ({config.default_agent})", "status": "configured"})
    elif config.use_local_llm:
        steps.append({"name": "Agent (Ollama local)", "status": "configured"})
    else:
        steps.append({
            "name": f"Agent ({config.default_agent})",
            "status": "warning",
            "reason": f"No API key for {config.default_agent}",
        })
    
    # Step 2: Write .env
    env_content = _generate_env(config)
    env_path = os.path.join(os.path.dirname(__file__), "..", ".env")
    with open(env_path, "w") as f:
        f.write(env_content)
    steps.append({"name": ".env file", "status": "written"})
    
    # Step 3: Pull repos
    if config.repos:
        repos = [r.strip() for r in config.repos.split(",") if r.strip()]
        workspaces_dir = os.getenv("WORKSPACES_DIR", "./workspaces")
        repos_dir = os.path.join(workspaces_dir, "repos")
        os.makedirs(repos_dir, exist_ok=True)
        
        for repo in repos:
            repo_name = repo.replace("/", "_")
            repo_path = os.path.join(repos_dir, repo_name)
            if not os.path.exists(repo_path):
                try:
                    subprocess.run(
                        ["git", "clone", f"https://github.com/{repo}.git", repo_path],
                        capture_output=True,
                        timeout=60,
                    )
                    steps.append({"name": f"Repo {repo}", "status": "cloned"})
                except Exception as e:
                    steps.append({"name": f"Repo {repo}", "status": "failed", "error": str(e)})
            else:
                steps.append({"name": f"Repo {repo}", "status": "already exists"})
    
    results["steps"] = steps
    results["success"] = True
    
    return results


def _generate_env(config: SetupConfig) -> str:
    """Generate .env file content from config."""
    lines = [
        "# Anant Intern Configuration",
        "# Generated by setup wizard",
        "",
        "# Slack",
        f"SLACK_BOT_TOKEN={config.slack_bot_token or ''}",
        f"SLACK_SIGNING_SECRET={config.slack_signing_secret or ''}",
        f"SLACK_APP_TOKEN={config.slack_app_token or ''}",
        "",
        "# GitHub",
        f"GITHUB_TOKEN={config.github_token or ''}",
        "",
        "# Jira",
        f"JIRA_URL={config.jira_url or ''}",
        f"JIRA_EMAIL={config.jira_email or ''}",
        f"JIRA_API_TOKEN={config.jira_api_token or ''}",
        f"JIRA_PROJECT_KEY={config.jira_project_key or ''}",
        "",
        "# Agent",
        f"DEFAULT_AGENT={config.default_agent}",
        f"AGENT_ROUTING={config.agent_routing}",
        "",
        "# API Keys",
        f"ANTHROPIC_API_KEY={config.anthropic_api_key or ''}",
        f"OPENAI_API_KEY={config.openai_api_key or ''}",
        f"XAI_API_KEY={config.xai_api_key or ''}",
        "",
        "# Local LLM",
        f"USE_LOCAL_LLM={'true' if config.use_local_llm else 'false'}",
        f"OLLAMA_BASE_URL={config.ollama_model}",
        "",
        "# Repos",
        f"REPOS={config.repos or ''}",
    ]
    return "\n".join(lines)
